//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace ConsolidadoDiario.Migrations
//{
//    [DbContext(typeof(ConsolidadoDbContext))]
//    [Migration("20240827163503_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.8")
//                .HasAnnotation("Relational:MaxIdentifierLength", 64);

//            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

//            modelBuilder.Entity("Lancamento", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("Data")
//                        .HasColumnType("datetime(6)");

//                    b.Property<int>("Tipo")
//                        .HasColumnType("int");

//                    b.Property<decimal>("Valor")
//                        .HasColumnType("decimal(65,30)");

//                    b.HasKey("Id");

//                    b.ToTable("lancamentos", (string)null);
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
